### ISSUE TITLE
Bdy (border-top+border-bottom) does not seem to work.

### ISSUE THREAD

**Issue by chhavi-khandelwal** [acss-io/atomizer#296] opened 2017-06-27 11:57 UTC
I used following atomic classes together.
Bdy(3px)  Bdbs(s)
But this does not seem to work. Browser does not show any rule regarding width of the border.
However, Bdw works.

**Comment by thierryk** [comment] 2017-06-27 16:56
You have a typo. It's **`BdY(3px)`**, not `Bdy(3px)`.

As a side note, the documentation contains a [whole section](https://acss.io/guides/helper-classes.html#-bd-borders-) about borders.

**Comment by tinder-rhsiao** [comment] 2017-06-28 06:03
@thierryk I think we only have `BdY` as a helper to create 1px border
https://github.com/acss-io/atomizer/blob/master/src/helpers.js#L25-L119

`BdY(3px)` probably wont work in this case

**Comment by roderickhsiao** [comment] 2017-06-28 06:30
@thierryk I think we only have `BdY` as a helper to create 1px border
https://github.com/acss-io/atomizer/blob/master/src/helpers.js#L25-L119

`BdY(3px)` probably wont work in this case

**Comment by chhavi-khandelwal** [comment] 2017-06-28 06:46
It works with BdY. Thanks!

**Comment by thierryk** [comment] 2017-06-28 15:53
cc @pankajparashar @renatoi @src-code 

Thanks @roderickhsiao. I'd copied/pasted @chhavi-khandelwal's code as-is and then simply replaced the `y` with a `Y`, leaving the extra bit :-(

As the doc shows, `BdY` does not take parameters, all helpers for borders are for a 1px border, as stated in the **Bd*** section I linked to:

> The default width of these [border] helpers is 1px as it is the most common use case. If you want to use a different width or style value, then you can either
>
>    * use standard Atomic classes, for example: `Bdw(5px) Bds(s) Bdc(#555)`

Good catch from @chhavi-khandelwal, we have typos on the [reference page](https://acss.io/reference). And it seems to be the case for most `Bd*` helpers actually (`BdX`, `BdY`, `BdT`, `BdEnd`, `BdB`, `BdStart`). I'll submit a PR.

As a side note, [Pankaj's tool](https://pankajparashar.com/atomizer-web/) shows that Atomizer plugs `Bd*` rules even if we use those classes with parameters, as in **`BdY(3px)`**. For example, `BdY(3px)` does create:

```css
.BdY {
  border-top-width: 1px;
  border-right-width: 0;
  border-bottom-width: 1px;
  border-left-width: 0;
  border-style: solid;
}
```

I don't think this could create problems though...

**Comment by thierryk** [comment] 2017-06-28 16:24
Closing this and opening an issue on acss-io/**acss-site**.

**Comment by src-code** [comment] 2017-06-28 17:09
@thierryk The problem here seems to be with the Bdy/Bdx/etc ruleset.  For rules like `Bdy` we have `allowParamToValue` set to `false`, which seems incorrect.  

Example:
```<div class="BdY Bdy(3px) BdX"></div>```

**Before:**
```css
.BdX {
  border-top-width: 0;
  border-right-width: 1px;
  border-bottom-width: 0;
  border-left-width: 1px;
}
.BdX, .BdY {
  border-style: solid;
}
.BdY {
  border-top-width: 1px;
  border-right-width: 0;
  border-bottom-width: 1px;
  border-left-width: 0;
}
```

**After:**

```css
.Bdy\(3px\) {
  border-top: 3px;
  border-bottom: 3px;
}
.BdX {
  border-top-width: 0;
  border-right-width: 1px;
  border-bottom-width: 0;
  border-left-width: 1px;
}
.BdX, .BdY {
  border-style: solid;
}
.BdY {
  border-top-width: 1px;
  border-right-width: 0;
  border-bottom-width: 1px;
  border-left-width: 0;
}
```

We don't expose helper classes in the reference tool, so searching for `BdY` will result in `Bdy` being returned since the search is case-insensitive.  Seems like we should expose helpers there to help clear up the confusion?

**Comment by src-code** [comment] 2017-06-28 17:11
Let's re-open this, since this seems to be an atomizer ruleset issue as well as a docs issue

**Comment by thierryk** [comment] 2017-06-28 17:15
@src-code and it seems the "matchers" are wrong in [rules.js](https://github.com/acss-io/atomizer/blob/5c207bf4b4f6d223e29409db78858ccb3375c9b4/src/rules.js#L226), isn't? So the  problem is only in this repo, the reference page using rules.js.

**Comment by thierryk** [comment] 2017-06-28 17:21
@src-code I don't think there is a problem with `allowParamToValue` as we're not supposed to allow params there. Or am I missing something?

We should not see things like:

```css
.Bdy\(3px\) {
  border-top: 3px;
  border-bottom: 3px;
}
```

My concern was about this:

```html
<div class="Bdy(3px)"></div>
```

```css
.BdY {
  border-top-width: 1px;
  border-right-width: 0;
  border-bottom-width: 1px;
  border-left-width: 0;
}
```

See what I mean?

**Comment by src-code** [comment] 2017-06-28 17:48
@thierryk Makes sense that we shouldn't get `BdY` if `allowParamToValue` is `false` - but what's the reason for not allowing param-to-value for `Bdy()`?  Why only allow custom values for those classes?

**Comment by thierryk** [comment] 2017-06-28 17:52
@src-code I replied to that question in [this comment](https://github.com/acss-io/atomizer/pull/297#issuecomment-311736521)

**Comment by src-code** [comment] 2017-06-28 17:55
> @src-code and it seems the "matchers" are wrong in rules.js, isn't? So the problem is only in this repo, the reference page using rules.js.

I don't think the matchers are wrong, here's what we've got:

helpers.js:
```
// Y axis
    {
        "type": "helper",
        "name": "Border Y 1px solid",
        "matcher": "BdY",
        "noParams": true,
        "styles": {
            "border-top-width": "1px",
            "border-right-width": 0,
            "border-bottom-width": "1px",
            "border-left-width": 0,
            "border-style": "solid"

        }
    },
```

rules.js:
```
{
        "type": "pattern",
        "name": "Border Y",
        "matcher": "Bdy",
        "allowParamToValue": false,
        "styles": {
            "border-top": "$0",
            "border-bottom": "$0"
        }
    },
```

**Comment by thierryk** [comment] 2017-06-28 17:59
How come in helper.js the matcher is `BdY` but `Bdy` in rules.js? I only assume the issue is there because the reference page is taking those strings from somewhere, no? Which file provides the strings if it's not rules.js? I can't find a match for `Bdy` anywhere else...

**Comment by src-code** [comment] 2017-06-28 18:02
@thierryk Reference page uses rules.js, and the search is case-insensitive.  So searching for Bdy or BdY will both return the definition of Bdy

**Comment by thierryk** [comment] 2017-06-28 18:18
@src-code yes, the search *should be* case-insensitive, we agree on that, but the problem is **with the result**: 

```html
Bdy(<custom-param>)
  border-top: value
  border-bottom: value
```
it should be:

```html
BdY
  border-top-width: 1px;
  border-right-width: 0;
  border-bottom-width: 1px;
  border-left-width: 0;
  border-style: solid;
```

That way people **know** the class they are supposed to use and what they are supposed to get.

Today, people searching for `BdY` or `Bdy` will use the latter because that's what the reference page shows. Actually, that result leads people to think that they need to:
   * use a lowercase `y`
   * use a parameter that will be used for `top` and `bottom` border--according to what they pass (`color`, `style`, or `width`).

**Comment by src-code** [comment] 2017-06-28 18:21
I would argue that we should just expose helpers and rules both, so the results returned should be:

```
Bdy(<custom-param>)
  border-top: value
  border-bottom: value

BdY
  border-top-width: 1px;
  border-right-width: 0;
  border-bottom-width: 1px;
  border-left-width: 0;
  border-style: solid;
```

But I seem to remember we specifically didn't want to include helpers in the reference page at one point for some reason, perhaps because they're not really Atomic classes?

**Comment by src-code** [comment] 2017-06-28 18:26
So to clarify - the reference page as it is today is correct, because a search for `Bdy` or `BdY` returns the *atomic* class `Bdy()`, which is a valid Atomic class.  Helpers like `BdY` are not searchable via the reference page today.

**Comment by thierryk** [comment] 2017-06-28 18:31
Dang! I think I've been retired for too long :)
Your comment reminded me that we **do have 2 different classes** (`BdY` **and** `Bdy()`). Doh!
And you're right, we used the lowercase and uppercase `y` to differentiate between the Atomic class from the helper class.

So either we'd need to expose both as you did in the comment above or we'd need to say something on the reference page about the fact that helper classes are not being exposed by the search tool?

**Comment by src-code** [comment] 2017-06-28 18:37
I'm thinking it's worth it to expose helper classes in the reference tool, but perhaps they can be labeled clearly with a link back to the Helpers doc page, so there's no confusing them with Atomic classes?

**Comment by src-code** [comment] 2017-06-28 18:51
Ok, I'm going to close this one out again in favor of https://github.com/acss-io/acss-site/issues/121

**Closed by src-code** 2017-06-28 18:51 UTC

**Comment by thierryk** [comment] 2017-06-28 18:59
Yeah, I think it's a good idea to make that very clear on the reference page so people don't get confused like I was through this thread ;-)

As a side note, may be we should have used a different naming convention for these helper classes so they'd have been easier to identify. For example using `h-Bdy` instead of `BdY` (simply pre-pending "h-" to the related Atomic class).
